// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define NOTOSANS_12_FONT_ID (-846830324)
#define NOTOSANS_14_FONT_ID (1528995761)
#define NOTOSANS_16_FONT_ID (-1135152666)
#define NOTOSANS_18_FONT_ID (-1632292195)
#define UI_10_FONT_ID (1883578066)
#define UI_12_FONT_ID (376639728)
#define SMALL_FONT_ID (-1860378437)
